### ISSUE TITLE
How to replace this EFI? when you cannot enter MacOS。如何更换这款EFI？当您无法进入MacOS时。

### ISSUE THREAD

**Issue by Bug-Pig** [Fansaly/X299-STRIX-macOS#2]
ROG STRIX X299-E GAMING

INTEL® CORE™ i9-7900X

Kingston 64bit 2400MHz 8GB x2

NVIDIA GeForce GTX 1060 6GB

SanDisk SDSSDHII 120G

Display resolution：1920x1080 75Hz

Logitech G502
Logitech G910

Intel(R) Ethernet Connection (2) I219-V
Realtek 8822BE Wireless LAN 802.11ac PCI-E NIC

BIOS has been set up, but cannot boot to the MacOS installation page, how to replace EFI, and what needs to be prepared.
BIOS已经设置完成，但无法引导至MacOS安装页，此时应如何替换EFI，以及需要准备什么工作。

**Comment by Fansaly** [comment]
### 安装准备

config.plist 使用仓库里提供的，并依照 [i9-7900X](https://www.tonymacx86.com/threads/how-to-build-your-own-imac-pro-successful-build-extended-guide.229353/page-986#post-1793896) 修改 ACPI/DSDT 相关部分。  
drivers 和 kexts 如下，此时不需要 ACPI patch 文件：
```
CLOVER
├── drivers
│   └── UEFI
│       ├── ApfsDriverLoader.efi
│       ├── AptioMemoryFix.efi
│       ├── FSInject.efi
│       ├── VBoxHfs.efi
│       └── VirtualSmc.efi
└── kexts
    └── Other
        ├── AppleALC.kext
        ├── IntelMausi.kext
        ├── Lilu.kext
        ├── TSCAdjustReset.kext
        ├── VirtualSMC.kext
        └── WhateverGreen.kext
```

### 完成安装后

- 需要修改 Hotpatch/SSDT-HDAU.dsl 中的 2 个 device-id，可能也需要修改端口数量。device-id 参考 Hotpatch/Device&ID.txt 获取。
- 或许需要适当调整 Hotpatch 设备的位置。

**Comment by Fansaly** [comment]
> ### 安装准备
> config.plist 使用仓库里提供的，并依照 [i9-7900X](https://www.tonymacx86.com/threads/how-to-build-your-own-imac-pro-successful-build-extended-guide.229353/page-986#post-1793896) 修改 ACPI/DSDT 相关部分。
> drivers 和 kexts 如下，此时不需要 ACPI patch 文件：
> 
> ```
> CLOVER
> ├── drivers
> │   └── UEFI
> │       ├── ApfsDriverLoader.efi
> │       ├── AptioMemoryFix.efi
> │       ├── FSInject.efi
> │       ├── VBoxHfs.efi
> │       └── VirtualSmc.efi
> └── kexts
>     └── Other
>         ├── AppleALC.kext
>         ├── IntelMausi.kext
>         ├── Lilu.kext
>         ├── TSCAdjustReset.kext
>         ├── VirtualSMC.kext
>         └── WhateverGreen.kext
> ```
> 
> ### 完成安装后
> * 需要修改 Hotpatch/SSDT-HDAU.dsl 中的 2 个 device-id，可能也需要修改端口数量。device-id 参考 Hotpatch/Device&ID.txt 获取。
> * 或许需要适当调整 Hotpatch 设备的位置。

`TSCAdjustReset.kext` 参考：https://github.com/Fansaly/X299-STRIX-macOS/blob/master/Kexts/README.md
