### ISSUE TITLE
请问Catalina版本下的EFI还有维护吗？

### ISSUE THREAD

**Issue by kiddtam** [Fansaly/X299-STRIX-macOS#3]

**Comment by Fansaly** [comment]
这台电脑只有 N卡，Catalina 不支持此 N卡，因此不曾安装高于 10.13.6 的 macOS，也就不曾维护更高系统下的 EFI。

**Comment by kiddtam** [comment]
> 这台电脑只有 N卡，Catalina 不支持此 N卡，因此不曾安装高于 10.13.6 的 macOS，也就不曾维护更高系统下的 EFI。

感谢回复~
