### ISSUE TITLE
请教CPU风扇问题

### ISSUE THREAD

**Issue by ztencmcp** [Fansaly/X299-STRIX-macOS#4]
请问，有没有出现如果先进苹果系统，CPU风扇的噪声很大。先进win系统，等风扇速度降下来后再进苹果系统就没问题。谢谢！

**Comment by Fansaly** [comment]
可以适当调整 AI Tweaker 下的 CPU Core Ratio
没有 macOS 版的 AI Sute，所以声音相比 Windows 要大些

**Comment by ztencmcp** [comment]
> 可以适当调整 AI Tweaker 下的 CPU Core Ratio
> 没有 macOS 版的 AI Sute，所以声音相比 Windows 要大些

谢谢大佬解答！
